### ISSUE TITLE
Specify the directory to be served

### ISSUE THREAD

**Issue by chr15m** [victrixsoft/bashbro#1]
By default it serves the root folder but it would be useful if you could specify the folder to be served and also if it defaulted to the current folder.

**Comment by tokenwizard** [comment]
+1
It seems unsafe to default to sharing the root folder. It should either default to the folder you run the command within, or take an argument to specify the folder to share. 

Apparently even though it is not run as root with sudo, you can still see the contents of /etc/passwd. So that seems really dangerous.

**Comment by tokenwizard** [comment]
Yeah, I'm going to go further and say that it should NOT share `/` by default AND should be limited to the folder/subfolders from which it is run or specified when running. There should not be a was to "go up a level" any higher than the one specified to share

**Comment by AdamDanischewski** [comment]
This was intended more of a quick and dirty kind of tool to grab or view a file. You have permissions of whatever user you run it as on the server. 

I guess you could then serve up a single directory or file, I'll probably add this in soon.

**Comment by tokenwizard** [comment]
I mean, there are probably a lot of use cases. One I could think of is:
Say you have a folder you just dumped a bunch of photos in and you want to be able to view them from any device in your home, via a web page. Just open a terminal and run `bashbro -sp5544 <photo_dir>` and BAM, good to go. 

Basically, being able to specify the folder to share would really only make the tool more flexible, and not have any downsides, that I can see.

**Comment by chr15m** [comment]
Most webserver tools default to serving the current directory. Here is a list of examples on Linux systems which follow this standard practice when starting a webserver:

```
busybox httpd -f -p 8080
python3 -m http.server
php -S 0.0.0.0:8000
npx http-server
yaws -i -S localhost
webfsd -Fp 8080
```

I don't know of any other webserver where the default is to serve the root folder of the machine. I mean it's your software so do what you want but it seems like odd behavior and the inability to set the folder being served limits the usefulness of an otherwise cool tool.

(Note: if you make it default to serving the current folder then you also solve the issue of not being able to set the directory since somebody can just cd into the directory they want to serve first.)

**Comment by AdamDanischewski** [comment]
I added a jail option, -j or long --jail. You can set it to current directory $PWD or any other dir. If you set it to a file it will only serve that particular file - (regardless of what url you put in). If you really are concerned about safety/security, I'd recommend creating a chroot for it.
