### ISSUE TITLE
on macos, it's missing the socat dependency and has the wrong getopt dependency

### ISSUE THREAD

**Issue by pmarreck** [victrixsoft/bashbro#2]
```
Wrong version of 'getopt' ..
Missing socat ..
Failed dependencies check, exiting ..
```

Since I use Nix to manage gnu/linux/posix deps on macos, fixing this was a simple matter of `nix profile install nixpkgs#getopt` and `nix profile install nixpkgs#socat` but maybe put a note in the README about it (they're probably also installable via Homebrew)

**Comment by AdamDanischewski** [comment]
It's hinted at the bottom of the Readme via shields, I don't have a Mac myself glad you got it to work.
